class_name Global
extends Node

enum ENEMIES {
	RED_SQUARE, BLUE_CIRCLE, GREEN_TRIANGLE, PINK_RING, YELLOW_TRIANGLE, PURPLE_HEXAGON, ORANGE_SQUARE
}

enum WEAPONS {
	REGULAR, DOUBLE, GROWING, HEAVY
}

enum PROJECTILES {
	REGULAR, CIRCLE, LASER
}
